.TH papersizes 7 "Noah's\ Documentation" "Noah\ Birnel"

.SH ANSI / Engineering Sizes
Each size is two pieces of the smaller size laid next to eachother.
Alternate sizes are proportionate \(em A, C, and E are of the proportion 22/17 (129%).
B and D are of the proportion 17/11 (154%) 

.PP
.RS
.TS
tab(,),box;
c,|c1,s1,s,|c
l,|r1,c1,l,|c.
Name,size in in.,common name
=
ANSI A,8.5,\(mu,11,letter
_
ANSI B,11,\(mu,17,ledger
_
ANSI C,17,\(mu,22,
_
ANSI D,22,\(mu,34,
_
ANSI E,34,\(mu,44,
.TE
.RE

.SH Architectural Sizes
As ANSI, each size is two pieces of the smaller size laid next to eachother.
Alternate sizes are proportionate \(em A, C, and E are of the proportion 4/3 (133%).
B and D are of the proportion 3/2 (150%).

.PP
.RS
.TS
tab(,),box;
c,|c1,s1,s
l,|r1,c1,l.
Name,size in in.
=
ARCH A,9,\(mu,12
_
ARCH B,12,\(mu,18
_
ARCH C,18,\(mu,24
_
ARCH D,24,\(mu,36
_
ARCH E,36,\(mu,48
.TE
.RE

.SH ISO & JIS A Series
Each size is square root of 2 (141%) larger than the smaller one.
The sizes are all proportionate \(em square root of 2 (141%).
Each size's short edge is the length of the smaller size's long edge.
.PP
A0 is one square meter.
.PP
.RS
.TS
tab(,),box;
c,|c1,s1,s
l,|r1,c1,l.
Name,size in mm.
=
A0,841,\(mu,1189
_
A1,594,\(mu,841
_
A2,420,\(mu,594
_
A3,297,\(mu,420
_
A4,210,\(mu,297
.TE
.RE
.SH ISO/DIN B Series
Each size is square root of 2 (141%) larger than the smaller one.
The sizes are all proportionate - square root of 2 (141%).
Each size's short edge is the length of the smaller size's long edge.
.PP
.RS
.TS
tab(,),box;
c,|c1,s1,s
l,|r1,c1,l.
Name,size in mm.,,
=
B0,1000,\(mu,1414
_
B1,707,\(mu,1000
_
B2,500,\(mu,707
_
B3,353,\(mu,500
_
B4,250,\(mu,353
_
B5,176,\(mu,297
.TE
.RE


.SH JIS B Series
Each size is square root of 2 (141%) larger than the smaller one.
The sizes are all proportionate - square root of 2 (141%).
Each size's short edge is the length of the smaller size's long edge.
.PP
JIS B0 is 1.5 square meters.
.PP
.RS
.TS
tab(,),box;
c,|c1,s1,s
l,|r1,c1,l.
Name,size in mm.,,
=
JIS B0,1030,\(mu,1456
_
JIS B1,728,\(mu,1030
_
JIS B2,515,\(mu,728
_
JIS B3,364,\(mu,515
_
JIS B4,257,\(mu,364
_
JIS B5,181,\(mu,257
.TE
.RE

.SH Misc Sizes
.PP
.RS
.TS
tab(,),box;
c,|c1,s1,s,|c,|c
l,|r1,c1,l,|c,|c.
Name,size in in.,common name,proportion
=
,8.5,\(mu,14,legal,28/17 (165%)
_
ARCH E1,30,\(mu,42,,7/5 (140%)
.TE
.RE

.SH Drilling
.SS 3 HD letter or ledger, left edge
.IP "\fB\(bu\fP"
4 \(14 in. on center
.IP "\fB\(bu\fP"
\(38 in. from edge
.IP "\fB\(bu\fP"
5/16 in. holes

.SS 2 HD letter or legal, top edge
.IP "\fB\(bu\fP"
2 \(34 in. on center
